# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# 中文为默认语言
zh:
  languageCode: zh-Hans
  title: 蔚芳空间智能工作室
  params:
    description: 蔚芳空间智能工作室 - 专注于城市规划、空间分析与生态环境研究
