# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# 中文为默认语言
zh:
  languageCode: zh-Hans
  title: "浙江大学蔚芳    WEL空间智能实验室" 
  params:
    description: 浙江大学蔚芳 WEL空间智能实验室(WEL Lab for Spatial Intelligence) - 专注于城市规划、空间分析与生态环境研究
