# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: /
    weight: 10
  - name: 专业课程
    url: course
    weight: 20
  - name: 团队成员
    url: people
    weight: 30
  - name: 学术活动
    url: event
    weight: 40
  - name: 学术论文
    url: publication
    weight: 50
  - name: 学术专著
    url: books
    weight: 60

